package:
    name: 
    version: ""

source:
    fn: 
    url: 
    md5: 

build:
    number: 0

requirements:
    build:
    run:

test:
    imports:

about:
    home: 
    license: 
    summary: ""
