package:
    name: libtheora
    version: "1.1.1"

source:
    fn: libtheora-1.1.1.tar.xz
    url: http://downloads.xiph.org/releases/theora/libtheora-1.1.1.tar.xz
    md5: 9eeabf1ad65b7f41533854a59f7a716d

build:
    number: 0

requirements:
    build:
        - libogg >=1.3.2
        - libvorbis >=1.3.5

    run:
        - libogg >=1.3.2
        - libvorbis >=1.3.5

about:
    home: https://xiph.org/theora/
    license: BSD
    summary: "Provides the functions to read and write video files."
