package:
    name: yasm
    version: "1.3.0"

source:
    git_url: git://github.com/yasm/yasm.git

build:
    number: 0

requirements:
    build:
        - python
        - automake

    run:
        - python

about:
    home: http://www.tortall.net/projects/yasm/
    license: BSD
    summary: 'Yasm is a complete rewrite of the NASM assembler under the "new" BSD License'
