package:
    name: libogg
    version: "1.3.2"

source:
    fn: http://downloads.xiph.org/releases/ogg/libogg-1.3.2.tar.xz
    url: http://downloads.xiph.org/releases/ogg/libogg-1.3.2.tar.xz
    md5: 5c3a34309d8b98640827e5d0991a4015

build:
    number: 0

about:
    home: https://xiph.org/ogg/
    license: BSD
    summary: "Provides the functions required for programs to read or write Ogg formatted bit streams."
