package:
    name: libvorbis
    version: "1.3.5"

source:
    fn: libvorbis-1.3.5.tar.xz
    url: http://downloads.xiph.org/releases/vorbis/libvorbis-1.3.5.tar.xz
    md5: 28cb28097c07a735d6af56e598e1c90f

build:
    number: 0

requirements:
    build:
        - libogg >=1.3.2

    run:
        - libogg >=1.3.2

about:
    home: https://xiph.org/vorbis/
    license: BSD
    summary: "Provides the functions used to read and write sound files."
