package:
    name: opus
    version: "1.1"

source:
    fn: opus-1.1.tar.gz
    url: http://downloads.xiph.org/releases/opus/opus-1.1.tar.gz
    md5: c5a8cf7c0b066759542bc4ca46817ac6

build:
    number: 0

requirements:
    build:
        - automake
        - autoconf

about:
    home: http://www.opus-codec.org/
    license: CCA-3
    summary: "Provides the functions used to read and write Opus format."
