package:
    name: x264
    version: "20141208.2245"

source:
    fn: x264-snapshot-20141208-2245-stable.tar.bz2
    url: http://download.videolan.org/pub/videolan/x264/snapshots/x264-snapshot-20141208-2245-stable.tar.bz2
    md5: f43e49099d7e8b572595429b9bfec636

build:
    number: 0

requirements:
    build:
        - yasm >=1.3.0
    run: 
        - yasm >=1.3.0

about:
    home: http://www.videolan.org/developers/x264.html
    license: GPL
    summary: "Provides the functions used to encode video streams into the H.264/MPEG-4 AVC format."
