package:
    name: libvpx
    version: "1.4.0"

source:
    fn: libvpx-1.4.0.tar.bz2
    url: http://storage.googleapis.com/downloads.webmproject.org/releases/webm/libvpx-1.4.0.tar.bz2
    md5: 63b1d7f59636a42eeeee9225cc14e7de

build:
    number: 0

requirements:
    build:
        - yasm >=1.3.0

    run:
        - yasm >=1.3.0

about:
    home: http://www.webmproject.org/code/
    license: BSD
    summary: "Provides functions to use the VP8 and VP9 video codecs."
