package:
    name: ffmpeg
    version: "2.6.2"

source:
    fn: ffmpeg-2.6.2.tar.bz2
    url: http://ffmpeg.org/releases/ffmpeg-2.6.2.tar.bz2
    md5: e75d598921285d6775f20164a91936ac

build:
    number: 0

requirements:
    build:
        - yasm >=1.3.0
        - x264 >=20141208.2245
        - fdk-aac >=0.1.4
        - freetype >=2.5.2
        - lame >=3.99.5
        - opus >=1.1
        - libvorbis >=1.3.5
        - libtheora >=1.1.1
        - libvpx >=1.4.0
    run: 
        - yasm >=1.3.0
        - freetype >=2.5.2
        - x264 >=20141208-2245
        - fdk-aac >=0.1.4
        - lame >=3.99.5
        - opus >=1.1
        - libvorbis >=1.3.5
        - libtheora >=1.1.1
        - libvpx >=1.4.0

about:
    home: https://www.ffmpeg.org/
    license: GPL2 
    summary: "A complete, cross-platform solution to record, convert and stream audio and video."
